/*
 * generated by Xtext
 */
package org.ovirt.engine.permissions.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.ovirt.engine.permissions.ui.internal.PermissionsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PermissionsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PermissionsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PermissionsActivator.getInstance().getInjector(PermissionsActivator.ORG_OVIRT_ENGINE_PERMISSIONS_PERMISSIONS);
	}
	
}
