/*
 * generated by Xtext
 */
package org.ovirt.engine.locks.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LocksUiModule extends org.ovirt.engine.locks.ui.AbstractLocksUiModule {
	public LocksUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
