/**
 * generated by Xtext 2.9.0
 */
package com.mucommander.auditing.scoping;

import com.mucommander.auditing.scoping.AbstractAuditLogScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class AuditLogScopeProvider extends AbstractAuditLogScopeProvider {
}
