/**
 * generated by Xtext 2.9.0
 */
package com.mucommander.auditing.scoping;

import com.google.inject.Inject;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.common.types.util.TypeReferences;
import org.eclipse.xtext.scoping.IScope;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class AuditLogScopeProvider /* implements AbstractAuditLogScopeProvider  */{
  @Inject
  private TypeReferences typeReferences;
  
  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field super is undefined"
      + "\nThe method or field super is undefined"
      + "\ngetScope cannot be resolved"
      + "\ngetScope cannot be resolved");
  }
}
