/*
 * generated by Xtext
 */
package org.ovirt.engine.locks.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.ovirt.engine.locks.ui.internal.LocksActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LocksExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LocksActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LocksActivator.getInstance().getInjector(LocksActivator.ORG_OVIRT_ENGINE_LOCKS_LOCKS);
	}
	
}
