/*
 * generated by Xtext
 */
package org.ovirt.engine.permissions.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractPermissionsValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.ovirt.engine.permissions.permissions.PermissionsPackage.eINSTANCE);
		return result;
	}
}
