/*
 * generated by Xtext
 */
package org.ovirt.engine.permissions.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PermissionsUiModule extends org.ovirt.engine.permissions.ui.AbstractPermissionsUiModule {
	public PermissionsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
