/**
 * generated by Xtext
 */
package org.ovirt.engine.permissions.ui.contentassist;

import org.ovirt.engine.permissions.ui.contentassist.AbstractPermissionsProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PermissionsProposalProvider extends AbstractPermissionsProposalProvider {
}
