/*
 * generated by Xtext
 */
package org.ovirt.engine.auditing.ui.contentassist

import org.ovirt.engine.auditing.ui.contentassist.AbstractAuditLogProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class AuditLogProposalProvider extends AbstractAuditLogProposalProvider {
}
