/*
 * generated by Xtext
 */
package org.ovirt.engine.locks;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LocksStandaloneSetup extends LocksStandaloneSetupGenerated{

	public static void doSetup() {
		new LocksStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

