/*
 * generated by Xtext
 */
package org.ovirt.engine.locks;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LocksRuntimeModule extends org.ovirt.engine.locks.AbstractLocksRuntimeModule {

}
