/*
 * generated by Xtext
 */
package org.ovirt.engine.locks;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LocksUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.ovirt.engine.locks.ui.internal.LocksActivator.getInstance().getInjector("org.ovirt.engine.locks.Locks");
	}
	
}
