/*
 * generated by Xtext
 */
package org.ovirt.engine.permissions.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.ovirt.engine.permissions.services.PermissionsGrammarAccess;

public class PermissionsParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PermissionsGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.ovirt.engine.permissions.parser.antlr.internal.InternalPermissionsParser createParser(XtextTokenStream stream) {
		return new org.ovirt.engine.permissions.parser.antlr.internal.InternalPermissionsParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public PermissionsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PermissionsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
