/*
 * generated by Xtext
 */
package org.ovirt.engine.permissions.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PermissionsAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/ovirt/engine/permissions/parser/antlr/internal/InternalPermissions.tokens");
	}
}
