/**
 * generated by Xtext 2.9.0
 */
package com.mucommander.auditing.ui;

import com.mucommander.auditing.ui.AbstractAuditLogUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AuditLogUiModule extends AbstractAuditLogUiModule {
  public AuditLogUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
