/**
 * generated by Xtext 2.9.0
 */
package com.mucommander.auditing.validation;

import com.mucommander.auditing.validation.AbstractAuditLogValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AuditLogValidator extends AbstractAuditLogValidator {
}
