/*
 * generated by Xtext
 */
package org.ovirt.engine.auditing;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AuditLogStandaloneSetup extends AuditLogStandaloneSetupGenerated{

	public static void doSetup() {
		new AuditLogStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

