/*
 * generated by Xtext
 */
package org.ovirt.engine.permissions;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PermissionsUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.ovirt.engine.permissions.ui.internal.PermissionsActivator.getInstance().getInjector("org.ovirt.engine.permissions.Permissions");
	}
	
}
