/**
 * generated by Xtext 2.9.0
 */
package com.mucommander.auditing;

import com.mucommander.auditing.SuppressingLinkingResource;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AuditLogRuntimeModule /* implements AbstractAuditLogRuntimeModule  */{
  @Override
  public Class<SuppressingLinkingResource> bindXtextResource() {
    return SuppressingLinkingResource.class;
  }
}
