/**
 * generated by Xtext 2.9.0
 */
package com.mucommander.auditing;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AuditLogStandaloneSetup /* implements AuditLogStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type AuditLogStandaloneSetup");
  }
}
