/**
 * generated by Xtext 2.9.0
 */
package com.mucommander.auditing;

import com.mucommander.auditing.AuditLogStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AuditLogStandaloneSetup extends AuditLogStandaloneSetupGenerated {
  public static void doSetup() {
    AuditLogStandaloneSetup _auditLogStandaloneSetup = new AuditLogStandaloneSetup();
    _auditLogStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
