/*
 * generated by Xtext
 */
package org.ovirt.engine.auditing.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AuditLogUiModule extends org.ovirt.engine.auditing.ui.AbstractAuditLogUiModule {
	public AuditLogUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
