/**
 * generated by Xtext
 */
package org.ovirt.engine.permissions.validation;

import org.ovirt.engine.permissions.validation.AbstractPermissionsValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PermissionsValidator extends AbstractPermissionsValidator {
}
