/*
 * generated by Xtext 2.9.0
 */
package com.mucommander.auditing


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AuditLogStandaloneSetup extends AuditLogStandaloneSetupGenerated {

	def static void doSetup() {
		new AuditLogStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
