/*
 * generated by Xtext
 */
package org.ovirt.engine.permissions;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PermissionsStandaloneSetup extends PermissionsStandaloneSetupGenerated{

	public static void doSetup() {
		new PermissionsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

