/*
 * generated by Xtext
 */
package org.ovirt.engine.permissions;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PermissionsRuntimeModule extends org.ovirt.engine.permissions.AbstractPermissionsRuntimeModule {

}
