/*
 * generated by Xtext
 */
package org.ovirt.engine.locks.ui.contentassist

import org.ovirt.engine.locks.ui.contentassist.AbstractLocksProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class LocksProposalProvider extends AbstractLocksProposalProvider {
}
